version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    command: npm run serve 
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 3000